spring :
  datasource:
    username: tily
    password: tily1234

  mail:
    username: rlatngus4789@gmail.com
    password: vpbiqmdyhqwxipgi

cloud:
  aws:
    credentials:
      access-key: AKIAXJFDYEG2DT2SCHD4
      secret-key: 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